#!/bin/sh -x
cd /tmp

ls='-u -p'
dmenu='-n'

selection=$(ls $ls | egrep '.*\..*\..*/' | dmenu $dmenu)
test -z "$selection" && exit 1
cd "$selection"
channels=$(stat -c "%Y %n" \#*/out | sort -r | cut -d" " -f 2 \
	  | grep -Eo ".*/" | cut -d/ -f 1)
channels="$channels
"$(stat -c "%Y %n" [^#]*/out | sort -r | cut -d" " -f 2 \
	  | grep -Eo ".*/" | cut -d/ -f 1)
selection=$(<<<"$channels" grep -Ev "(^irc|^global$|^nickserv$|^py-ctcp$)" \
	| dmenu $dmenu)

test -z "$selection" && exit 1
cd "$selection"
while 	text=$(</dev/null dmenu -p "${selection%/}" \
		| sed -r 's|^/me (.*)$|ACTION \1|')
	[ -n "$text" ]
do	printf "%s\n" "$text" > in
done
